# Generated by Django 3.1.12 on 2025-08-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precapp', '0001_make_precatorio_fields_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precatorio',
            name='percentual_contratuais_apartado',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='precatorio',
            name='percentual_contratuais_assinado',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='precatorio',
            name='percentual_sucumbenciais',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
