# Generated by Django 3.1.12 on 2025-08-30 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precatorio',
            name='credito_principal',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('quitado', 'Quitado'), ('vendido', 'Vendido')], default='pendente', help_text='Status de pagamento do crédito principal', max_length=20),
        ),
        migrations.AlterField(
            model_name='precatorio',
            name='honorarios_contratuais',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('quitado', 'Quitado'), ('vendido', 'Vendido')], default='pendente', help_text='Status de pagamento dos honorários contratuais', max_length=20),
        ),
        migrations.AlterField(
            model_name='precatorio',
            name='honorarios_sucumbenciais',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('quitado', 'Quitado'), ('vendido', 'Vendido')], default='pendente', help_text='Status de pagamento dos honorários sucumbenciais', max_length=20),
        ),
        migrations.AlterField(
            model_name='precatorio',
            name='orcamento',
            field=models.IntegerField(blank=True, help_text='Ano do orçamento (formato: YYYY)', null=True, validators=[django.core.validators.MinValueValidator(1988), django.core.validators.MaxValueValidator(2050)]),
        ),
    ]
