# Generated by Django 5.2.6 on 2025-09-10 16:14

import precapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='precatorio',
            name='integra_precatorio_filename',
            field=models.CharField(blank=True, help_text='Nome original do arquivo da íntegra', max_length=255, null=True, verbose_name='Nome do arquivo original'),
        ),
        migrations.AlterField(
            model_name='alvara',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='diligencias',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fasehonorarioscontratuais',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pedidorequerimento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='precatorio',
            name='integra_precatorio',
            field=models.FileField(blank=True, help_text='Íntegra do precatório em PDF (máximo 50MB)', null=True, upload_to='precatorios/integras/%Y/%m/', validators=[precapp.models.validate_file_size, precapp.models.validate_pdf_extension], verbose_name='Íntegra do precatório'),
        ),
        migrations.AlterField(
            model_name='requerimento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tipodiligencia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
