# Generated by Django 3.1.12 on 2025-08-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('precapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precatorio',
            name='acordo_deferido',
        ),
    ]
