# Generated by Django 3.1.12 on 2025-08-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alvara',
            name='honorarios_contratuais',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='alvara',
            name='honorarios_sucumbenciais',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
