# Generated by Django 5.2.6 on 2025-09-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='precatorio',
            name='integra_precatorio_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que a íntegra do precatório foi enviada', null=True, verbose_name='Data de upload da íntegra'),
        ),
    ]
