# Generated by Django 3.1.12 on 2025-08-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alvara',
            name='fase_alterada_por',
            field=models.CharField(blank=True, help_text='Usuário que fez a última alteração da fase principal', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='alvara',
            name='fase_honorarios_alterada_por',
            field=models.CharField(blank=True, help_text='Usuário que fez a última alteração da fase de honorários contratuais', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='alvara',
            name='fase_honorarios_ultima_alteracao',
            field=models.DateTimeField(blank=True, help_text='Data e hora da última alteração da fase de honorários contratuais', null=True),
        ),
        migrations.AddField(
            model_name='alvara',
            name='fase_ultima_alteracao',
            field=models.DateTimeField(blank=True, help_text='Data e hora da última alteração da fase principal', null=True),
        ),
        migrations.AddField(
            model_name='requerimento',
            name='fase_alterada_por',
            field=models.CharField(blank=True, help_text='Usuário que fez a última alteração da fase', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='requerimento',
            name='fase_ultima_alteracao',
            field=models.DateTimeField(blank=True, help_text='Data e hora da última alteração da fase', null=True),
        ),
    ]
