# Generated by Django 5.2.6 on 2025-09-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precapp', '0002_precatorio_integra_precatorio_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='falecido',
            field=models.BooleanField(blank=True, help_text='Indica se o cliente está falecido', null=True, verbose_name='Falecido(a)'),
        ),
        migrations.AlterField(
            model_name='precatorio',
            name='credito_principal',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('quitado', 'Quitado'), ('vendido', 'Vendido'), ('inaplicável', 'Inaplicável')], default='pendente', help_text='Status de pagamento do crédito principal', max_length=20),
        ),
        migrations.AlterField(
            model_name='precatorio',
            name='honorarios_contratuais',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('quitado', 'Quitado'), ('vendido', 'Vendido'), ('inaplicável', 'Inaplicável')], default='pendente', help_text='Status de pagamento dos honorários contratuais', max_length=20),
        ),
        migrations.AlterField(
            model_name='precatorio',
            name='honorarios_sucumbenciais',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('quitado', 'Quitado'), ('vendido', 'Vendido'), ('inaplicável', 'Inaplicável')], default='pendente', help_text='Status de pagamento dos honorários sucumbenciais', max_length=20),
        ),
    ]
